USE [master]
GO
/****** Object:  Database [studentinfo]    Script Date: 2023/11/21 16:27:03 ******/
CREATE DATABASE [studentinfo]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'studentinfo', FILENAME = N'D:\Database_Local\studentinfo.mdf' , SIZE = 10240KB , MAXSIZE = 102400KB , FILEGROWTH = 5%)
 LOG ON 
( NAME = N'studentinfo_log', FILENAME = N'D:\Database_Local\studentinfo_log.ldf' , SIZE = 4096KB , MAXSIZE = 30720KB , FILEGROWTH = 1024KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [studentinfo] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [studentinfo].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [studentinfo] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [studentinfo] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [studentinfo] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [studentinfo] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [studentinfo] SET ARITHABORT OFF 
GO
ALTER DATABASE [studentinfo] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [studentinfo] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [studentinfo] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [studentinfo] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [studentinfo] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [studentinfo] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [studentinfo] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [studentinfo] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [studentinfo] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [studentinfo] SET  ENABLE_BROKER 
GO
ALTER DATABASE [studentinfo] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [studentinfo] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [studentinfo] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [studentinfo] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [studentinfo] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [studentinfo] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [studentinfo] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [studentinfo] SET RECOVERY FULL 
GO
ALTER DATABASE [studentinfo] SET  MULTI_USER 
GO
ALTER DATABASE [studentinfo] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [studentinfo] SET DB_CHAINING OFF 
GO
ALTER DATABASE [studentinfo] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [studentinfo] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [studentinfo] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [studentinfo] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'studentinfo', N'ON'
GO
ALTER DATABASE [studentinfo] SET QUERY_STORE = ON
GO
ALTER DATABASE [studentinfo] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200)
GO
USE [studentinfo]
GO
/****** Object:  Table [dbo].[class]    Script Date: 2023/11/21 16:27:04 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[class](
	[classno] [char](8) NOT NULL,
	[classinfo] [varchar](50) NULL,
PRIMARY KEY CLUSTERED 
(
	[classno] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[course]    Script Date: 2023/11/21 16:27:04 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[course](
	[cno] [char](4) NOT NULL,
	[cname] [varchar](20) NULL,
	[credit] [float] NULL,
PRIMARY KEY CLUSTERED 
(
	[cno] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[score]    Script Date: 2023/11/21 16:27:04 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[score](
	[sno] [char](12) NOT NULL,
	[cno] [char](4) NOT NULL,
	[sscore] [float] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[sno] ASC,
	[cno] ASC,
	[sscore] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[student]    Script Date: 2023/11/21 16:27:04 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[student](
	[sno] [char](12) NOT NULL,
	[sname] [char](10) NOT NULL,
	[classno] [char](7) NULL,
	[sbirthday] [datetime] NULL,
	[ssex] [char](2) NULL,
PRIMARY KEY CLUSTERED 
(
	[sno] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Table_1]    Script Date: 2023/11/21 16:27:04 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Table_1](
	[sno] [nchar](10) NULL,
	[snb] [nchar](10) NULL
) ON [PRIMARY]
GO
USE [master]
GO
ALTER DATABASE [studentinfo] SET  READ_WRITE 
GO
